version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: "build(deps): "

    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: "chore(deps): "
    schedule:
      interval: daily
    ignore:
      - dependency-name: "semantic-release"
        versions: ["20.x", "21.x"]
